module.exports={
    'stateGradeSemester':[
        {
            name:"小学",
            grade:[
                {id:0,name:'一年级'},
                {id:1,name:'二年级'},
                {id:2,name:'三年级'},
                {id:3,name:'四年级'},
                {id:4,name:'五年级'},
                {id:5,name:'六年级'}
            ],
            term:[
                
                {id:1,name:'一年级上学期'},
                {id:2,name:'一年级下学期'},
                {id:3,name:'二年级上学期'},
                {id:4,name:'二年级下学期'},
                {id:5,name:'三年级上学期'},
                {id:6,name:'三年级下学期'},
                {id:7,name:'四年级上学期'},
                {id:8,name:'四年级下学期'},
                {id:9,name:'五年级上学期'},
                {id:10,name:'五年级下学期'},
                {id:11,name:'六年级上学期'},
                {id:12,name:'六年级下学期'}
            ]
        },
        {
            name:"初中",
            grade:[
                {id:6,name:'七年级'},
                {id:7,name:'八年级'},
                {id:8,name:'九年级'}
            ],
            term:[
                {id:13,name:'七年级上学期'},
                {id:14,name:'七年级下学期'},
                {id:15,name:'八年级上学期'},
                {id:16,name:'八年级下学期'},
                {id:17,name:'九年级上学期'},
                {id:18,name:'九年级下学期'}
            ]
        }
    ]
}